services:
  - type: web
    name: college-chatbot-api
    env: python
    plan: free
    # This is the crucial line for your structure
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app"
    envVars:
      - key: PYTHON_VERSION
        value: '3.12'