services:
  - type: web
    name: college-chatbot-api
    env: python
    plan: free
    # This is the crucial line for your structure
    rootDir: backend
    pythonVersion: '3.12'
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app"
    envVars:
      - key: PYTHON_VERSION
        value: '3.12'
      # Remember to set your secrets in the Render Dashboard, not here.
      - key: DATABASE_URL
        generateValue: true # Example if using a Render DB